rootProject.name = "CloudstreamPlugins"

// This file sets what projects are included. Every time you add a new project, you must add it
// to the includes below.

// Plugins are included like this
include(
    "XcineProvider",
    "StreamingcommunityProvider",
    "FilmanProvider",
    "VMoveeProvider",
    "AsiaFlixProvider",
    "DoramasYTProvider",
//    "SflixProProvider",
    "PinoyMoviePediaProvider",
    "SeriesflixProvider",
    "TrailersTwoProvider",
    "PinoyMoviesEsProvider",
    "KisskhProvider",
    "DramaSeeProvider",
    "VidstreamProviderTemplate",
    "RebahinProvider",
    "AllMoviesForYouProvider",
    "UakinoProvider",
    "DramaidProvider",
    "FaselHDProvider",
    "MeloMovieProvider",
    "PelisplusProvider",
    "AsianLoadProvider",
    "YomoviesProvider",
    "AkwamProvider",
    "VidEmbedProvider",
    "IdlixProvider",
    "NginxProvider",
    "SoaptwoDayProvider",
    "PinoyHDXyzProvider",
    "AltadefinizioneProvider",
    "PelisflixProvider",
    "SflixProvider",
    "ElifilmsProvider",
    "VidSrcProvider",
    "EgyBestProvider",
    "WatchAsianProvider",
    "VfSerieProvider",
    "LayarKacaProvider",
    "EntrepeliculasyseriesProvider",
    "TantiFilmProvider",
    "TwoEmbedProvider",
    "SuperStream",
    "FilmpertuttiProvider",
    "FrenchStreamProvider",
    "KdramaHoodProvider",
    "MyCimaProvider",
    "IlGenioDelloStreamingProvider",
    "EstrenosDoramasProvider",
//    "HDTodayProvider",
    "DopeboxProvider",
    "DubokuProvider",
    "HDMProvider",
    "PhimmoichillProvider",
    "PelisplusProviderTemplate",
    "OlgplyProvider",
    "SolarmovieProvider",
    "PeliSmartProvider",
    "VfFilmProvider",
    "IHaveNoTvProvider",
    "CuevanaProvider",
    "CinecalidadProvider",
    "HDMovie5",
    "HDrezkaProvider",
    "PelisplusHDProvider",
    "MultiplexProvider",
    "OpenVidsProvider",
    //"BflixProvider",
//    "FmoviesToProvider",
    "TheFlixToProvider",
)
